{"uuid":"abd6faaf-6c2a-4fc5-bc8f-3ee47aff7d16","historyId":"f4f5a0f9820f115728300293d9326408","fullName":"testapi.TestForSampleAPIPOSTTest.validateCreateUserEndPointWithEmailNoDomain","labels":[{"name":"package","value":"testapi.TestForSampleAPIPOSTTest"},{"name":"testClass","value":"testapi.TestForSampleAPIPOSTTest"},{"name":"testMethod","value":"validateCreateUserEndPointWithEmailNoDomain"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"apc"},{"name":"subSuite","value":"testapi.TestForSampleAPIPOSTTest"},{"name":"host","value":"Sailajas-MacBook-Pro.local"},{"name":"thread","value":"75681@Sailajas-MacBook-Pro.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"To Create User email with no domain","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":" Mismatch Json Response expected [true] but found [false]","trace":"java.lang.AssertionError:  Mismatch Json Response expected [true] but found [false]\n\tat org.testng.Assert.fail(Assert.java:99)\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\n\tat org.testng.Assert.assertTrue(Assert.java:45)\n\tat testapi.TestForSampleAPIPOSTTest.validateCreateUserEndPointWithEmailNoDomain(TestForSampleAPIPOSTTest.java:80)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:794)\n\tat org.testng.TestRunner.run(TestRunner.java:596)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:377)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:276)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1134)\n\tat org.testng.TestNG.runSuites(TestNG.java:1063)\n\tat org.testng.TestNG.run(TestNG.java:1031)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\n"},"stage":"finished","description":"Description : Testing Create User Endpoint , whether Exception though with HTTP Status 400","steps":[],"attachments":[],"parameters":[],"start":1635082216051,"stop":1635082219899}